"use strict";
exports.__esModule = true;
exports.tCollectionsListResponseDataSchema = exports.tCollectionFieldsSchema = exports.tTokenFieldsSchema = exports.tCurationFieldsSchema = exports.tCollectionsListQueryDataSchema = exports.tTokenUrlFieldsSchema = exports.tTokenMediaItemFieldsSchema = exports.tCurationSelectionSchema = exports.tRecordDefaultFieldsSchema = exports.tPaginatedEndpointQueryDataSchema = void 0;
// Generated by ts-to-zod
var zod_1 = require("zod");
exports.tPaginatedEndpointQueryDataSchema = zod_1.z.object({
    skip: zod_1.z.number(),
    take: zod_1.z.number()
});
exports.tRecordDefaultFieldsSchema = zod_1.z.object({
    id: zod_1.z.string(),
    createdAt: zod_1.z.string(),
    updatedAt: zod_1.z.string()
});
exports.tCurationSelectionSchema = zod_1.z.object({
    type: zod_1.z.number(),
    collectionId: zod_1.z.string().optional(),
    curationId: zod_1.z.string().optional(),
    content: zod_1.z.string().optional()
});
exports.tTokenMediaItemFieldsSchema = zod_1.z.object({
    type: zod_1.z.string(),
    mime: zod_1.z.string(),
    url: zod_1.z.string()
});
exports.tTokenUrlFieldsSchema = zod_1.z.object({
    type: zod_1.z.string(),
    url: zod_1.z.string()
});
exports.tCollectionsListQueryDataSchema = exports.tPaginatedEndpointQueryDataSchema.and(zod_1.z.object({}));
exports.tCurationFieldsSchema = zod_1.z.object({
    publishedAt: zod_1.z.string().optional(),
    curationSelections: zod_1.z.array(exports.tCurationSelectionSchema)
});
exports.tTokenFieldsSchema = zod_1.z.object({
    title: zod_1.z.string(),
    description: zod_1.z.string(),
    tokenMediaItems: zod_1.z.array(exports.tTokenMediaItemFieldsSchema),
    tokenUrls: zod_1.z.array(exports.tTokenUrlFieldsSchema)
});
exports.tCollectionFieldsSchema = zod_1.z.object({
    networkName: zod_1.z.string(),
    contractAddress: zod_1.z.string(),
    thumbnailUrl: zod_1.z.string(),
    title: zod_1.z.string(),
    description: zod_1.z.string(),
    tokens: zod_1.z.array(exports.tTokenFieldsSchema)
});
exports.tCollectionsListResponseDataSchema = zod_1.z.object({
    collections: zod_1.z.array(exports.tCollectionFieldsSchema)
});
